let express=require("express")
const { adduser, login, islogin, isadmin } = require("../controlers/usercont")
const { upload, add, getprod, upddct, deldct, updprod, updpimg, getprodbyid, addrv, delprod } = require("../controlers/prodcont")
const { addcart, getcart, delcart, decqty, incqty } = require("../controlers/cartcont")
let route=new express.Router()
route.post("/adduser",adduser)
route.post("/login",login)
route.post("/addprod",upload.single("pimg"),islogin,isadmin,add)
route.get("/getprod",getprod)
route.get("/getprodbyid/:pid",getprodbyid)
route.put("/upddct",upddct)
route.put("/deldct",deldct)
route.put("/updprod",upload.single("pimg"),updprod)
route.put("/updimg",upload.single("pimg"),updpimg)
route.post("/addcart",addcart)
route.get("/getcart/:uid",islogin,getcart)
route.put("/inc",incqty)
route.put("/dec",decqty)
route.put("/addrv",addrv)
route.delete("/delcart/:id",delcart)
route.delete("/delprod/:pid",delprod)
module.exports=route